### ISSUE TITLE
Further Instructions

### ISSUE THREAD

**Issue by cmurrayis** [chromedp/chromedp-proxy#2]
Hi,

Wondering if there have been any further work on this, I'm looking for a solution to capture communications between an application and the chrome instances this launches. I cannot modify the requst to Chrome to set the logging destination however your app appears to do what I need however unclear.

**Comment by kenshaw** [comment]
@cmurrayis this proxy works just fine. I use it on a fairly regular basis.

**Comment by cmurrayis** [comment]
Thanks @kenshaw Does it do what I've described? The description isn't 100% clear to me.

App | > Chrome
..........|  > Chrome
..........|  > Chrome
..........|  > Chrome
..........|  > Chrome

Needing to capture all that traffic without adjusting any settings in Chrome or the App.
